#!/bin/sh
#The template for compiling 

#https://github.com/Neo-Oli/termux-ubuntu References # EMPIRESSERVERHEADER
echo PARAM DEBUG ${currdir} ${currentexecfile}
if [ -z ${currdir} ] ;then
export currdir=$(pwd)
fi
#This prevent new instances to overwrite current directory causes multiple problems
if [ -z ${currentexecfile} ] ;then
export currentexecfile=${0}
fi
which(){
busybox which $1
}

########################################################## Install Logic ############################################33

#if [ $(whoami) != root ]; then
#echo Please re run this compile script with root
#echo Thank you
#exit
#fi
if [ ! -d containersys ] || [ $(cat empiresservercontainer/buildnumber) -lt 6969696 ] ; then
lineno=86 #This line is the position of the md5hash stored #Please Change this Number to successfully compiles +2 from last line
initorigindir=$(pwd)
integrity=$(sed -n "${lineno}p" "$0") #https://stackoverflow.com/questions/21651310/reading-a-particular-line-from-a-file-in-bash-script-using-variable-as-line-numb
echo "${integrity}" > hash
echo Preparing package empires-server
echo Pulling Package from the script
if [ -z $(which busybox) ]; then echo no busybox detected toybox unsupported ; exit ;fi
echo 'Preparing For installation'
tail -n +51 $0 > unifiedContainer-package #Please Change this Number to successfully compiles +3 from last line IF 87 Line then 89
if md5sum -c hash ; then
echo Archive Integrity Verified
rm hash
else
echo It is altered or ruined thus installation is aborted
rm hash
fi
tar -xf unifiedContainer-package
rm -rf unifiedContainer-package ; echo Installation Successfull
fi
#####################################################################################################################



exit
EOF