#!/bin/sh
#The template for compiling 

#https://github.com/Neo-Oli/termux-ubuntu References # EMPIRESSERVERHEADER
echo PARAM DEBUG ${currdir} ${currentexecfile}
if [ -z ${currdir} ] ;then
export currdir=$(pwd)
fi
#This prevent new instances to overwrite current directory causes multiple problems
if [ -z ${currentexecfile} ] ;then
export currentexecfile=${0}
fi
which(){
busybox which $1
}

########################################################## Install Logic ############################################33
if [ ! -d containersys ] || [ $(cat empiresservercontainer/buildnumber) -lt 6969696 ] ; then
lineno=48 #This line is the position of the md5hash stored #Please Change this Number to successfully compiles +1 from last line
initorigindir=$(pwd)
integrity=$(sed -n "${lineno}p" "$0") #https://stackoverflow.com/questions/21651310/reading-a-particular-line-from-a-file-in-bash-script-using-variable-as-line-numb
echo "${integrity}" > hash
echo Preparing bin
echo Pulling Package from the script
if [ -z $(which busybox) ]; then echo no busybox detected toybox unsupported ; echo "Bypassing! Limitation" ;fi
echo 'Preparing For installation'
tail -n +49 $0 > bin #Please Change this Number to successfully compiles +2 from last line IF 87 Line then 89
if md5sum -c hash ; then
echo Archive Integrity Verified
rm hash
else
echo "Modified Program!, Exiting"
rm hash ; exit
fi
tar -xf bin
rm -rf bin ; echo Installation Successful
fi
#####################################################################################################################
echo "#!/bin/sh" > launcher
echo "sh $(pwd)/bashloader \$@" >> launcher
echo "#!/bin/sh" > $0
echo "sh $(pwd)/bashloader \$@" >> $0
chmod +x launcher; chmod +x $0
# leave a blank space after the EOF line to make sure the md5hash does not merge with EOF ( empires-server compiler issue )
./launcher
exit
EOF #################################################################################################################
