#!/bin/sh
export PATH="$(pwd)/bashstaticengine:${PATH}"
 case $(uname -m) in
		aarch64)
			archfile_bash="aarch64" ;;
		arm)
			archfile_bash="armv7" ;;
		amd64)
			archfile_bash="x86_64";;
		i*86)
			archfile_bash="i486"; echo "32 bit Intel system is currently not included on the package, we are required your system to be included with bash already"; ;;
		*86_64)
			archfile_bash="x86_64" ;;
		*)
			echo "Unsupported Architecture, Sorry!"; exit 69 ;;
		esac
echo "Initializing Bash to be usable"
rm -rf $(pwd)/bashstaticengine/bash
cp $(pwd)/bashstaticengine/bash-${archfile_bash} $(pwd)/bashstaticengine/bash
if [ -z $(which bash)]; then
echo "No Bash Runtime Detected, Failure Imminent! Please install Bash on your distro"
exit
fi
echo "Bash Successfully Initialized! Handing over to the main routines unifyServer"
chmod +x $(pwd)/unifyServer
bash $(pwd)/unifyServer $@